name: Update EC2 via SSM

on:
  workflow_dispatch:
    inputs:
      instance-id:
        description: "EC2 Instance ID to update"
        required: true
jobs:
  update-ec2:
    runs-on: [self-hosted, test]

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Send SSM Command to EC2
        run: |
          aws ssm send-command \
            --instance-ids i-01d97a06fdd70609e \
            --document-name "AWS-RunPatchBaseline" \
            --comment "Update system" \
            --parameters '{"Operation":["Install"]}' \
            --timeout-seconds 600 \
            --query "Command.CommandId" \
            --output text
            
      # - name: Get Command ID
      #   id: command
      #   run: |
      #     CMD_ID=$(aws ssm list-commands --query "Commands[0].CommandId" --output text)
      #     echo "command_id=$CMD_ID" >> "$GITHUB_OUTPUT"

      # - name: Wait and Get Output
      #   run: |
      #     sleep 10  # adjust based on command time
      #     aws ssm get-command-invocation \
      #       --command-id ${{ steps.command.outputs.command_id }} \
      #       --instance-id i-01d97a06fdd70609e   
